namespace TasksApp
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.pltask = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnUp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnAddTask = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.dateTask = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.btnAdd = new Bunifu.UI.WinForms.BunifuImageButton();
            this.btnExit = new Bunifu.UI.WinForms.BunifuImageButton();
            this.txtDatiels = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pltask.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.AutoScroll = true;
            this.flowLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowLayoutPanel1.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(0, 102);
            this.flowLayoutPanel1.Margin = new System.Windows.Forms.Padding(0);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(320, 473);
            this.flowLayoutPanel1.TabIndex = 1;
            // 
            // pltask
            // 
            this.pltask.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            this.pltask.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pltask.BackgroundImage")));
            this.pltask.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pltask.BorderColor = System.Drawing.Color.Transparent;
            this.pltask.BorderRadius = 3;
            this.pltask.BorderThickness = 1;
            this.pltask.Controls.Add(this.btnUp);
            this.pltask.Controls.Add(this.label1);
            this.pltask.Controls.Add(this.bunifuButton22);
            this.pltask.Controls.Add(this.btnAddTask);
            this.pltask.Controls.Add(this.dateTask);
            this.pltask.Controls.Add(this.btnAdd);
            this.pltask.Controls.Add(this.btnExit);
            this.pltask.Controls.Add(this.txtDatiels);
            this.pltask.Controls.Add(this.txtName);
            this.pltask.Controls.Add(this.bunifuTextBox1);
            this.pltask.Dock = System.Windows.Forms.DockStyle.Top;
            this.pltask.Location = new System.Drawing.Point(0, 0);
            this.pltask.Name = "pltask";
            this.pltask.ShowBorders = true;
            this.pltask.Size = new System.Drawing.Size(320, 102);
            this.pltask.TabIndex = 0;
            // 
            // btnUp
            // 
            this.btnUp.AllowAnimations = true;
            this.btnUp.AllowMouseEffects = true;
            this.btnUp.AllowToggling = false;
            this.btnUp.AnimationSpeed = 200;
            this.btnUp.AutoGenerateColors = false;
            this.btnUp.AutoRoundBorders = false;
            this.btnUp.AutoSizeLeftIcon = true;
            this.btnUp.AutoSizeRightIcon = true;
            this.btnUp.BackColor = System.Drawing.Color.Transparent;
            this.btnUp.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            this.btnUp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUp.BackgroundImage")));
            this.btnUp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUp.ButtonText = "";
            this.btnUp.ButtonTextMarginLeft = 0;
            this.btnUp.ColorContrastOnClick = 45;
            this.btnUp.ColorContrastOnHover = 45;
            this.btnUp.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnUp.CustomizableEdges = borderEdges1;
            this.btnUp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUp.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUp.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUp.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnUp.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnUp.ForeColor = System.Drawing.Color.White;
            this.btnUp.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUp.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUp.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUp.IconMarginLeft = 11;
            this.btnUp.IconPadding = 10;
            this.btnUp.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUp.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUp.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.btnUp.IconSize = 32;
            this.btnUp.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.btnUp.IdleBorderRadius = 5;
            this.btnUp.IdleBorderThickness = 1;
            this.btnUp.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            this.btnUp.IdleIconLeftImage = null;
            this.btnUp.IdleIconRightImage = global::TasksApp.Properties.Resources.upload;
            this.btnUp.IndicateFocus = false;
            this.btnUp.Location = new System.Drawing.Point(253, 171);
            this.btnUp.Margin = new System.Windows.Forms.Padding(0);
            this.btnUp.Name = "btnUp";
            this.btnUp.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUp.OnDisabledState.BorderRadius = 5;
            this.btnUp.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUp.OnDisabledState.BorderThickness = 1;
            this.btnUp.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUp.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUp.OnDisabledState.IconLeftImage = null;
            this.btnUp.OnDisabledState.IconRightImage = null;
            this.btnUp.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.btnUp.onHoverState.BorderRadius = 5;
            this.btnUp.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUp.onHoverState.BorderThickness = 1;
            this.btnUp.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btnUp.onHoverState.ForeColor = System.Drawing.Color.Transparent;
            this.btnUp.onHoverState.IconLeftImage = null;
            this.btnUp.onHoverState.IconRightImage = null;
            this.btnUp.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.btnUp.OnIdleState.BorderRadius = 5;
            this.btnUp.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUp.OnIdleState.BorderThickness = 1;
            this.btnUp.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            this.btnUp.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUp.OnIdleState.IconLeftImage = null;
            this.btnUp.OnIdleState.IconRightImage = global::TasksApp.Properties.Resources.upload;
            this.btnUp.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.btnUp.OnPressedState.BorderRadius = 5;
            this.btnUp.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUp.OnPressedState.BorderThickness = 1;
            this.btnUp.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btnUp.OnPressedState.ForeColor = System.Drawing.Color.Transparent;
            this.btnUp.OnPressedState.IconLeftImage = null;
            this.btnUp.OnPressedState.IconRightImage = null;
            this.btnUp.Size = new System.Drawing.Size(36, 33);
            this.btnUp.TabIndex = 7;
            this.btnUp.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUp.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUp.TextMarginLeft = 0;
            this.btnUp.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUp.UseDefaultRadiusAndThickness = true;
            this.btnUp.Click += new System.EventHandler(this.btnUp_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Tajawal Black", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.label1.Location = new System.Drawing.Point(62, 13);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(151, 24);
            this.label1.TabIndex = 6;
            this.label1.Text = "Tasks Management";
            // 
            // bunifuButton22
            // 
            this.bunifuButton22.AllowAnimations = true;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = true;
            this.bunifuButton22.AnimationSpeed = 200;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = false;
            this.bunifuButton22.AutoSizeLeftIcon = true;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
            this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.ButtonText = "";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges2;
            this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton22.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton22.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 10;
            this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.bunifuButton22.IconSize = 32;
            this.bunifuButton22.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.bunifuButton22.IdleBorderRadius = 10;
            this.bunifuButton22.IdleBorderThickness = 1;
            this.bunifuButton22.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.IdleIconLeftImage = null;
            this.bunifuButton22.IdleIconRightImage = global::TasksApp.Properties.Resources.clear_2_;
            this.bunifuButton22.IndicateFocus = true;
            this.bunifuButton22.Location = new System.Drawing.Point(205, 171);
            this.bunifuButton22.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.OnDisabledState.BorderRadius = 10;
            this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnDisabledState.BorderThickness = 1;
            this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.bunifuButton22.onHoverState.BorderRadius = 10;
            this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.onHoverState.BorderThickness = 1;
            this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.bunifuButton22.onHoverState.IconLeftImage = null;
            this.bunifuButton22.onHoverState.IconRightImage = global::TasksApp.Properties.Resources.clear_3_;
            this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.bunifuButton22.OnIdleState.BorderRadius = 10;
            this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnIdleState.BorderThickness = 1;
            this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnIdleState.IconLeftImage = null;
            this.bunifuButton22.OnIdleState.IconRightImage = global::TasksApp.Properties.Resources.clear_2_;
            this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.bunifuButton22.OnPressedState.BorderRadius = 10;
            this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnPressedState.BorderThickness = 1;
            this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.bunifuButton22.OnPressedState.IconLeftImage = null;
            this.bunifuButton22.OnPressedState.IconRightImage = global::TasksApp.Properties.Resources.clear_3_;
            this.bunifuButton22.Size = new System.Drawing.Size(36, 33);
            this.bunifuButton22.TabIndex = 5;
            this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            this.bunifuButton22.Click += new System.EventHandler(this.bunifuButton22_Click);
            // 
            // btnAddTask
            // 
            this.btnAddTask.AllowAnimations = true;
            this.btnAddTask.AllowMouseEffects = true;
            this.btnAddTask.AllowToggling = true;
            this.btnAddTask.AnimationSpeed = 200;
            this.btnAddTask.AutoGenerateColors = false;
            this.btnAddTask.AutoRoundBorders = false;
            this.btnAddTask.AutoSizeLeftIcon = true;
            this.btnAddTask.AutoSizeRightIcon = true;
            this.btnAddTask.BackColor = System.Drawing.Color.Transparent;
            this.btnAddTask.BackColor1 = System.Drawing.Color.Transparent;
            this.btnAddTask.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddTask.BackgroundImage")));
            this.btnAddTask.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAddTask.ButtonText = "";
            this.btnAddTask.ButtonTextMarginLeft = 0;
            this.btnAddTask.ColorContrastOnClick = 45;
            this.btnAddTask.ColorContrastOnHover = 45;
            this.btnAddTask.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnAddTask.CustomizableEdges = borderEdges3;
            this.btnAddTask.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddTask.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddTask.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddTask.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddTask.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnAddTask.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnAddTask.ForeColor = System.Drawing.Color.White;
            this.btnAddTask.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddTask.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddTask.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.btnAddTask.IconMarginLeft = 11;
            this.btnAddTask.IconPadding = 10;
            this.btnAddTask.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddTask.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddTask.IconRightPadding = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.btnAddTask.IconSize = 32;
            this.btnAddTask.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.btnAddTask.IdleBorderRadius = 10;
            this.btnAddTask.IdleBorderThickness = 1;
            this.btnAddTask.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnAddTask.IdleIconLeftImage = null;
            this.btnAddTask.IdleIconRightImage = global::TasksApp.Properties.Resources.sticker_1_;
            this.btnAddTask.IndicateFocus = true;
            this.btnAddTask.Location = new System.Drawing.Point(157, 171);
            this.btnAddTask.Margin = new System.Windows.Forms.Padding(0);
            this.btnAddTask.Name = "btnAddTask";
            this.btnAddTask.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddTask.OnDisabledState.BorderRadius = 10;
            this.btnAddTask.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAddTask.OnDisabledState.BorderThickness = 1;
            this.btnAddTask.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddTask.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddTask.OnDisabledState.IconLeftImage = null;
            this.btnAddTask.OnDisabledState.IconRightImage = null;
            this.btnAddTask.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.btnAddTask.onHoverState.BorderRadius = 10;
            this.btnAddTask.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAddTask.onHoverState.BorderThickness = 1;
            this.btnAddTask.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btnAddTask.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.btnAddTask.onHoverState.IconLeftImage = null;
            this.btnAddTask.onHoverState.IconRightImage = global::TasksApp.Properties.Resources.sticker;
            this.btnAddTask.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.btnAddTask.OnIdleState.BorderRadius = 10;
            this.btnAddTask.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAddTask.OnIdleState.BorderThickness = 1;
            this.btnAddTask.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnAddTask.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddTask.OnIdleState.IconLeftImage = null;
            this.btnAddTask.OnIdleState.IconRightImage = global::TasksApp.Properties.Resources.sticker_1_;
            this.btnAddTask.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.btnAddTask.OnPressedState.BorderRadius = 10;
            this.btnAddTask.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAddTask.OnPressedState.BorderThickness = 1;
            this.btnAddTask.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btnAddTask.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.btnAddTask.OnPressedState.IconLeftImage = null;
            this.btnAddTask.OnPressedState.IconRightImage = global::TasksApp.Properties.Resources.sticker;
            this.btnAddTask.Size = new System.Drawing.Size(36, 33);
            this.btnAddTask.TabIndex = 5;
            this.btnAddTask.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddTask.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddTask.TextMarginLeft = 0;
            this.btnAddTask.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddTask.UseDefaultRadiusAndThickness = true;
            this.btnAddTask.Click += new System.EventHandler(this.btnAddTask_Click);
            // 
            // dateTask
            // 
            this.dateTask.BackColor = System.Drawing.Color.Transparent;
            this.dateTask.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.dateTask.BorderRadius = 6;
            this.dateTask.CalendarMonthBackground = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            this.dateTask.Color = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.dateTask.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thick;
            this.dateTask.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dateTask.DisabledColor = System.Drawing.Color.Gray;
            this.dateTask.DisplayWeekNumbers = false;
            this.dateTask.DPHeight = 0;
            this.dateTask.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dateTask.FillDatePicker = false;
            this.dateTask.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dateTask.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.dateTask.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dateTask.Icon = ((System.Drawing.Image)(resources.GetObject("dateTask.Icon")));
            this.dateTask.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.dateTask.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dateTask.LeftTextMargin = 5;
            this.dateTask.Location = new System.Drawing.Point(26, 172);
            this.dateTask.MinimumSize = new System.Drawing.Size(4, 32);
            this.dateTask.Name = "dateTask";
            this.dateTask.Size = new System.Drawing.Size(103, 32);
            this.dateTask.TabIndex = 4;
            this.dateTask.Value = new System.DateTime(2024, 6, 22, 8, 57, 0, 0);
            // 
            // btnAdd
            // 
            this.btnAdd.ActiveImage = global::TasksApp.Properties.Resources.plus_2_;
            this.btnAdd.AllowAnimations = true;
            this.btnAdd.AllowBuffering = false;
            this.btnAdd.AllowToggling = false;
            this.btnAdd.AllowZooming = false;
            this.btnAdd.AllowZoomingOnFocus = false;
            this.btnAdd.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            this.btnAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAdd.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnAdd.ErrorImage")));
            this.btnAdd.FadeWhenInactive = false;
            this.btnAdd.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnAdd.Image = global::TasksApp.Properties.Resources.plus_3_;
            this.btnAdd.ImageActive = global::TasksApp.Properties.Resources.plus_2_;
            this.btnAdd.ImageLocation = null;
            this.btnAdd.ImageMargin = 0;
            this.btnAdd.ImageSize = new System.Drawing.Size(32, 32);
            this.btnAdd.ImageZoomSize = new System.Drawing.Size(32, 32);
            this.btnAdd.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnAdd.InitialImage")));
            this.btnAdd.Location = new System.Drawing.Point(266, 55);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Rotation = 0;
            this.btnAdd.ShowActiveImage = true;
            this.btnAdd.ShowCursorChanges = false;
            this.btnAdd.ShowImageBorders = false;
            this.btnAdd.ShowSizeMarkers = false;
            this.btnAdd.Size = new System.Drawing.Size(32, 32);
            this.btnAdd.TabIndex = 0;
            this.btnAdd.ToolTipText = "Add Task";
            this.btnAdd.WaitOnLoad = false;
            this.btnAdd.Zoom = 0;
            this.btnAdd.ZoomSpeed = 10;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            // 
            // btnExit
            // 
            this.btnExit.ActiveImage = null;
            this.btnExit.AllowAnimations = true;
            this.btnExit.AllowBuffering = false;
            this.btnExit.AllowToggling = false;
            this.btnExit.AllowZooming = true;
            this.btnExit.AllowZoomingOnFocus = false;
            this.btnExit.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            this.btnExit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExit.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnExit.ErrorImage")));
            this.btnExit.FadeWhenInactive = false;
            this.btnExit.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnExit.Image = global::TasksApp.Properties.Resources.power_off_1_;
            this.btnExit.ImageActive = null;
            this.btnExit.ImageLocation = null;
            this.btnExit.ImageMargin = 0;
            this.btnExit.ImageSize = new System.Drawing.Size(24, 24);
            this.btnExit.ImageZoomSize = new System.Drawing.Size(25, 25);
            this.btnExit.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnExit.InitialImage")));
            this.btnExit.Location = new System.Drawing.Point(290, 5);
            this.btnExit.Name = "btnExit";
            this.btnExit.Rotation = 0;
            this.btnExit.ShowActiveImage = true;
            this.btnExit.ShowCursorChanges = true;
            this.btnExit.ShowImageBorders = true;
            this.btnExit.ShowSizeMarkers = false;
            this.btnExit.Size = new System.Drawing.Size(25, 25);
            this.btnExit.TabIndex = 2;
            this.btnExit.ToolTipText = "App Exit";
            this.btnExit.WaitOnLoad = false;
            this.btnExit.Zoom = 0;
            this.btnExit.ZoomSpeed = 10;
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            // 
            // txtDatiels
            // 
            this.txtDatiels.AcceptsReturn = false;
            this.txtDatiels.AcceptsTab = false;
            this.txtDatiels.AnimationSpeed = 200;
            this.txtDatiels.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDatiels.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDatiels.AutoSizeHeight = true;
            this.txtDatiels.BackColor = System.Drawing.Color.Transparent;
            this.txtDatiels.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDatiels.BackgroundImage")));
            this.txtDatiels.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.txtDatiels.BorderColorDisabled = System.Drawing.Color.White;
            this.txtDatiels.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.txtDatiels.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.txtDatiels.BorderRadius = 10;
            this.txtDatiels.BorderThickness = 2;
            this.txtDatiels.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtDatiels.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDatiels.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDatiels.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDatiels.DefaultText = "";
            this.txtDatiels.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            this.txtDatiels.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.txtDatiels.HideSelection = true;
            this.txtDatiels.IconLeft = null;
            this.txtDatiels.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDatiels.IconPadding = 10;
            this.txtDatiels.IconRight = null;
            this.txtDatiels.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDatiels.Lines = new string[0];
            this.txtDatiels.Location = new System.Drawing.Point(157, 108);
            this.txtDatiels.Margin = new System.Windows.Forms.Padding(0);
            this.txtDatiels.MaxLength = 32767;
            this.txtDatiels.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDatiels.Modified = false;
            this.txtDatiels.Multiline = false;
            this.txtDatiels.Name = "txtDatiels";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDatiels.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.White;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDatiels.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDatiels.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            stateProperties4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDatiels.OnIdleState = stateProperties4;
            this.txtDatiels.Padding = new System.Windows.Forms.Padding(3);
            this.txtDatiels.PasswordChar = '\0';
            this.txtDatiels.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.txtDatiels.PlaceholderText = "Detials";
            this.txtDatiels.ReadOnly = false;
            this.txtDatiels.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDatiels.SelectedText = "";
            this.txtDatiels.SelectionLength = 0;
            this.txtDatiels.SelectionStart = 0;
            this.txtDatiels.ShortcutsEnabled = true;
            this.txtDatiels.Size = new System.Drawing.Size(144, 47);
            this.txtDatiels.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDatiels.TabIndex = 3;
            this.txtDatiels.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDatiels.TextMarginBottom = 0;
            this.txtDatiels.TextMarginLeft = 3;
            this.txtDatiels.TextMarginTop = 1;
            this.txtDatiels.TextPlaceholder = "Detials";
            this.txtDatiels.UseSystemPasswordChar = false;
            this.txtDatiels.WordWrap = true;
            // 
            // txtName
            // 
            this.txtName.AcceptsReturn = false;
            this.txtName.AcceptsTab = false;
            this.txtName.AnimationSpeed = 200;
            this.txtName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtName.AutoSizeHeight = true;
            this.txtName.BackColor = System.Drawing.Color.Transparent;
            this.txtName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtName.BackgroundImage")));
            this.txtName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.txtName.BorderColorDisabled = System.Drawing.Color.White;
            this.txtName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.txtName.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.txtName.BorderRadius = 10;
            this.txtName.BorderThickness = 2;
            this.txtName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtName.DefaultText = "";
            this.txtName.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            this.txtName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.txtName.HideSelection = true;
            this.txtName.IconLeft = null;
            this.txtName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.IconPadding = 10;
            this.txtName.IconRight = null;
            this.txtName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.Lines = new string[0];
            this.txtName.Location = new System.Drawing.Point(26, 108);
            this.txtName.Margin = new System.Windows.Forms.Padding(0);
            this.txtName.MaxLength = 32767;
            this.txtName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtName.Modified = false;
            this.txtName.Multiline = false;
            this.txtName.Name = "txtName";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.White;
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            stateProperties8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnIdleState = stateProperties8;
            this.txtName.Padding = new System.Windows.Forms.Padding(3);
            this.txtName.PasswordChar = '\0';
            this.txtName.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.txtName.PlaceholderText = "Name";
            this.txtName.ReadOnly = false;
            this.txtName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtName.SelectedText = "";
            this.txtName.SelectionLength = 0;
            this.txtName.SelectionStart = 0;
            this.txtName.ShortcutsEnabled = true;
            this.txtName.Size = new System.Drawing.Size(115, 47);
            this.txtName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtName.TabIndex = 2;
            this.txtName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtName.TextMarginBottom = 0;
            this.txtName.TextMarginLeft = 3;
            this.txtName.TextMarginTop = 1;
            this.txtName.TextPlaceholder = "Name";
            this.txtName.UseSystemPasswordChar = false;
            this.txtName.WordWrap = true;
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.AutoSizeHeight = true;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.White;
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.bunifuTextBox1.BorderRadius = 10;
            this.bunifuTextBox1.BorderThickness = 2;
            this.bunifuTextBox1.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox1.DefaultText = "";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            this.bunifuTextBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            this.bunifuTextBox1.HideSelection = true;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[0];
            this.bunifuTextBox1.Location = new System.Drawing.Point(26, 46);
            this.bunifuTextBox1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.White;
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(56)))), ((int)(((byte)(69)))));
            stateProperties12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(185)))), ((int)(((byte)(206)))));
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.bunifuTextBox1.OnIdleState = stateProperties12;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox1.PasswordChar = '\0';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(87)))), ((int)(((byte)(107)))));
            this.bunifuTextBox1.PlaceholderText = "Searh In Tasks";
            this.bunifuTextBox1.ReadOnly = false;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 0;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(224, 47);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox1.TabIndex = 1;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 3;
            this.bunifuTextBox1.TextMarginTop = 1;
            this.bunifuTextBox1.TextPlaceholder = "Searh In Tasks";
            this.bunifuTextBox1.UseSystemPasswordChar = false;
            this.bunifuTextBox1.WordWrap = true;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 18F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(27)))), ((int)(((byte)(33)))));
            this.ClientSize = new System.Drawing.Size(320, 575);
            this.Controls.Add(this.flowLayoutPanel1);
            this.Controls.Add(this.pltask);
            this.Font = new System.Drawing.Font("Tajawal Medium", 9.749999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Tasks Manager";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.pltask.ResumeLayout(false);
            this.pltask.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuPanel pltask;
        public Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private Bunifu.UI.WinForms.BunifuImageButton btnExit;
        private Bunifu.UI.WinForms.BunifuImageButton btnAdd;
        public Bunifu.UI.WinForms.BunifuTextBox txtDatiels;
        public Bunifu.UI.WinForms.BunifuTextBox txtName;
        public Bunifu.UI.WinForms.BunifuDatePicker dateTask;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAddTask;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnUp;
    }
}

